#cloud-config

# Launch instance with network interfaces configured to the local IP addresses we references in the config.
# $ aws ec2 run-instances --user-data file://aspera.yml --iam-instance-profile Name="encoded-instance" --image-id ami-5a928a3b --region us-west-2 --security-groups ssh-http-https --instance-type c4.xlarge


bootcmd:
- cloud-init-per once ssh-users-ca echo "TrustedUserCAKeys /etc/ssh/users_ca.pub" >> /etc/ssh/sshd_config

output:
  all: '| tee -a /var/log/cloud-init-output.log'

packages:
- fuse
- golang
- git
- awscli
- curl
- ntp

runcmd:

- set -ex
- systemctl daemon-reload
- mkdir -p /s3/encode-files
- mkdir -p /s3/encoded-files-dev

## - curl -sS -L -o /usr/local/bin/goofys https://github.com/kahing/goofys/releases/download/v0.0.4/goofys
- curl -sS -L -o /usr/local/bin/goofys https://s3-us-west-1.amazonaws.com/encoded-build/goofys/goofys-aee8168
- chmod +x /usr/local/bin/goofys

## - mkdir -p /opt/goofys/bin
## - chown -R build:build /opt/goofys
## - sudo -u build GOPATH=/opt/goofys go get github.com/kahing/goofys
## - mv /opt/goofys/bin/goofys /usr/local/bin/

- mount -a
- mkdir -p /opt/aspera
- cd /opt/aspera
- curl -s http://demo.asperasoft.com/ascp-install-3.5.4.102989-linux-64.sh > aspera.script.sh
- sudo sh aspera.script.sh

users:
- default
- name: build
  gecos: Build user
  inactive: true
  system: true

mounts:
- [ "goofys#encode-files", "/s3/encode-files", "fuse", "_netdev,allow_other,--file-mode=0444,--dir-mode=0555,--stat-cache-ttl=0", "0", "0" ]
- [ "goofys#encoded-files-dev", "/s3/encoded-files-dev", "fuse", "_netdev,allow_other,--file-mode=0444,--dir-mode=0555,--stat-cache-ttl=0", "0", "0" ]

write_files:
- path: /etc/ssh/users_ca.pub
  content: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAv/ymOcnN4LhM4NACc3Or116XXJ6KytuOgB/+1qNkOFBqBosrn7cmJ35rsoNHRgYNrCsRE9ch74RKsN6H72FtSJgBhGh/9oUK7Os6Fqt3/ZZXxgxIx6ubs/MTgrxrAnujiBxUXMXQhLKMriNMpo8mt4nGYVtLk9PBjiyfncaS8H9ZKoNio9dhP8bmTuYvioAI35dqKdSlVLyzr/XkZxia8Ki+pQ0N6uuiEwMR3ToM+LSp8wpFOOAiu4PEAujRW7us/+1hlpKWfn0J7/V3826joHE+I967Vg/+ikcVhF77JjK1nib879VgCWfmn1HPQosIpk4yJfVgGvRVI7I2nfBPVw== encoded@demo-l.encodedcc.org
- path: /etc/systemd/system/cloud-final.service.d/override.conf
  content: |
    [Service]
    # See https://bugs.launchpad.net/cloud-init/+bug/1449318
    KillMode=process
